package com.yinhe.susproject.model;

// Generated 2015-5-11 19:44:16 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Packagefile generated by hbm2java
 */
@Entity
@Table(name = "packagefile", catalog = "db3")
public class Packagefile implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4893774875727647042L;
	private Long id;
	private Packages packages;
	private Long filesize;
	private Date time;
	private String location;
	private String fileType;

	public Packagefile() {
	}

	public Packagefile(Packages packages, Long filesize, Date time,
			String location, String fileType) {
		this.packages = packages;
		this.filesize = filesize;
		this.time = time;
		this.location = location;
		this.fileType = fileType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "packageId",  nullable = false)
	public Packages getPackages() {
		return this.packages;
	}

	public void setPackages(Packages packages) {
		this.packages = packages;
	}

	@Column(name = "filesize",  nullable = false)
	public Long getFilesize() {
		return this.filesize;
	}

	public void setFilesize(Long filesize) {
		this.filesize = filesize;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time", length = 10)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@Column(name = "location",  nullable = false)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "fileType", length = 2, nullable = false)
	public String getFileType() {
		return this.fileType;
	}

	public void setFileType(String fileType) {
		this.fileType = fileType;
	}

}
