package com.yinhe.susproject.model;

// Generated 2015-5-11 19:44:16 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;


import org.hibernate.validator.constraints.NotEmpty;

/**
 * Packages generated by hbm2java
 */
@Entity
@Table(name = "packages", catalog = "db3", uniqueConstraints = @UniqueConstraint(columnNames = {
		"hardwareId", "factoryId", "softwareId" }))
public class Packages implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3327626778438619075L;
	private Long id;
	private Users users;
	private int factoryId;
	private String hardwareId;
	private String softwareId;
	private String deversion;
	private String trailStage;
	private String active;
	private String discription;
	private Set<Packagefile> packagefiles = new HashSet<Packagefile>(0);

	public Packages() {
	}

	public Packages(int factoryId) {
		this.factoryId = factoryId;
	}

	public Packages(Users users, int factoryId, String hardwareId,
			String softwareId, String deversion,String trailStage, String active,
			String discription, Set<Packagefile> packagefiles) {
		this.users = users;
		this.factoryId = factoryId;
		this.hardwareId = hardwareId;
		this.softwareId = softwareId;
		this.deversion  = deversion;
		this.trailStage = trailStage;
		this.active = active;
		this.discription = discription;
		this.packagefiles = packagefiles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "factoryId", nullable = false)
	
	public int getFactoryId() {
		return this.factoryId;
	}

	public void setFactoryId(int factoryId) {
		this.factoryId = factoryId;
	}

	@Column(name = "hardwareId", length = 64, nullable = false)
	public String getHardwareId() {
		return this.hardwareId;
	}

	public void setHardwareId(String hardwareId) {
		this.hardwareId = hardwareId;
	}

	@Column(name = "softwareId",  nullable = false)
	@NotEmpty
	public String getSoftwareId() {
		return this.softwareId;
	}

	public void setSoftwareId(String softwareId) {
		this.softwareId = softwareId;
	}
	
	@Column(name = "deversion")
	public String getDeversion() {
		return this.deversion;
	}

	public void setDeversion(String deversion) {
		this.deversion = deversion;
	}

	@Column(name = "trailStage", length = 2)
	public String getTrailStage() {
		return this.trailStage;
	}

	public void setTrailStage(String trailStage) {
		this.trailStage = trailStage;
	}

	@Column(name = "active", length = 2, nullable = false)
	public String getActive() {
		return this.active;
	}

	public void setActive(String active) {
		this.active = active;
	}

	@Column(name = "discription")
	public String getDiscription() {
		return this.discription;
	}

	public void setDiscription(String discription) {
		this.discription = discription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "packages")
	public Set<Packagefile> getPackagefiles() {
		return this.packagefiles;
	}

	public void setPackagefiles(Set<Packagefile> packagefiles) {
		this.packagefiles = packagefiles;
	}

}
