package com.yinhe.susproject.model;

// Generated 2015-5-11 19:44:16 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Rulesn generated by hbm2java
 */
@Entity
@Table(name = "rulesn", catalog = "db3", uniqueConstraints = @UniqueConstraint(columnNames = {
		"schId", "sn" }))
public class Rulesn implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8742133992905301322L;
	private Long id;
	private Schedule schedule;
	private long sn;
	private String enable;

	public Rulesn() {
	}

	public Rulesn(Schedule schedule, long sn) {
		this.schedule = schedule;
		this.sn = sn;
	}

	public Rulesn(Schedule schedule, long sn, String enable) {
		this.schedule = schedule;
		this.sn = sn;
		this.enable = enable;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "schId", nullable = false)
	public Schedule getSchedule() {
		return this.schedule;
	}

	public void setSchedule(Schedule schedule) {
		this.schedule = schedule;
	}

	@Column(name = "sn", nullable = false)
	public long getSn() {
		return this.sn;
	}

	public void setSn(long sn) {
		this.sn = sn;
	}

	@Column(name = "enable", length = 2)
	public String getEnable() {
		return this.enable;
	}

	public void setEnable(String enable) {
		this.enable = enable;
	}

}
