package com.yinhe.susproject.model;

// Generated 2015-5-11 19:44:16 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Rulerange generated by hbm2java
 */
@Entity
@Table(name = "rulerange", catalog = "db3", uniqueConstraints = @UniqueConstraint(columnNames = {
		"schId", "startMAC", "endMAC", "startSN", "endSN" }))
public class Rulerange implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5344880366056825724L;
	private Long id;
	private Schedule schedule;
	private Long startMac;
	private Long endMac;
	private String macInclude;
	private String startSn;
	private String endSn;
	private String snInclude;

	public Rulerange() {
	}

	public Rulerange(Schedule schedule) {
		this.schedule = schedule;
	}

	public Rulerange(Schedule schedule, Long startMac, Long endMac,
			String macInclude, String startSn, String endSn, String snInclude) {
		this.schedule = schedule;
		this.startMac = startMac;
		this.endMac = endMac;
		this.macInclude = macInclude;
		this.startSn = startSn;
		this.endSn = endSn;
		this.snInclude = snInclude;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "schId", nullable = false)
	public Schedule getSchedule() {
		return this.schedule;
	}

	public void setSchedule(Schedule schedule) {
		this.schedule = schedule;
	}

	@Column(name = "startMAC")
	public Long getStartMac() {
		return this.startMac;
	}

	public void setStartMac(Long startMac) {
		this.startMac = startMac;
	}

	@Column(name = "endMAC")
	public Long getEndMac() {
		return this.endMac;
	}

	public void setEndMac(Long endMac) {
		this.endMac = endMac;
	}

	@Column(name = "macInclude", length = 2)
	public String getMacInclude() {
		return this.macInclude;
	}

	public void setMacInclude(String macInclude) {
		this.macInclude = macInclude;
	}

	@Column(name = "startSN",length = 64)
	public String getStartSn() {
		return this.startSn;
	}

	public void setStartSn(String startSn) {
		this.startSn = startSn;
	}

	@Column(name = "endSN",length = 64)
	public String getEndSn() {
		return this.endSn;
	}

	public void setEndSn(String endSn) {
		this.endSn = endSn;
	}

	@Column(name = "snInclude", length = 2)
	public String getSnInclude() {
		return this.snInclude;
	}

	public void setSnInclude(String snInclude) {
		this.snInclude = snInclude;
	}

}
