package com.yinhe.susproject.model;

// Generated 2015-5-11 19:44:16 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Rulemac generated by hbm2java
 */
@Entity
@Table(name = "rulemac", catalog = "db3", uniqueConstraints = @UniqueConstraint(columnNames = {
		"schId", "mac" }))
public class Rulemac implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2435703167974611090L;
	private Long id;
	private Schedule schedule;
	private long mac;
	private String enable;

	public Rulemac() {
	}

	public Rulemac(Schedule schedule, long mac) {
		this.schedule = schedule;
		this.mac = mac;
	}

	public Rulemac(Schedule schedule, long mac, String enable) {
		this.schedule = schedule;
		this.mac = mac;
		this.enable = enable;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "schId", nullable = false)
	public Schedule getSchedule() {
		return this.schedule;
	}

	public void setSchedule(Schedule schedule) {
		this.schedule = schedule;
	}

	@Column(name = "mac", nullable = false)
	public long getMac() {
		return this.mac;
	}

	public void setMac(long mac) {
		this.mac = mac;
	}

	@Column(name = "enable", length = 2)
	public String getEnable() {
		return this.enable;
	}

	public void setEnable(String enable) {
		this.enable = enable;
	}

}
