package com.yinhe.susproject.model;

// Generated 2015-5-11 19:44:16 by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotEmpty;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "userroles", catalog = "db3", uniqueConstraints = @UniqueConstraint(columnNames = "username"))
public class UserRoles implements java.io.Serializable {


	/**
	 * 
	 */
	private static final long serialVersionUID = -5362517702719949326L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	
	@NotNull
	@NotEmpty
	@Column(name = "username", unique = true, length = 20)	
	private String username;
	
	@NotNull
	@NotEmpty
	private String role;
	

	public UserRoles() {
	}

	public UserRoles(String username, String role) {
		this.username = username;
		this.role = role;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}


	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getRole() {
		return role;
	}

	public void setRole(String role) {
		this.role = role;
	}
	
}
