package com.yinhe.susproject.model;

// Generated 2015-5-11 19:44:16 by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;

import org.hibernate.validator.constraints.NotEmpty;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "db3", uniqueConstraints = @UniqueConstraint(columnNames = "username"))
public class Users implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6660895811371383829L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	
	@NotNull
	@NotEmpty
	@Pattern(regexp = "[0-9a-zA-Z]{1,}", message = "字母数字下划线组合！")
	@Column(name = "username", unique = true, length = 20)	
	private String username;
	
	@NotNull
	@NotEmpty
	private String passwdhash;
	
	@Pattern(regexp = "\\w+@\\w+.\\w+", message = "电子邮件格式不正确！")
	@Column(name = "email", unique = true, length = 20)	
	private String email;
	
	@Pattern(regexp = "\\d{6,}", message = "电话格式不正确，至少6位数字！")
	@Column(name = "phone", unique = true, length = 20)	
	private String phone;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	private Set<Packages> packageses = new HashSet<Packages>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	private Set<Schedule> schedules = new HashSet<Schedule>(0);

	public Users() {
	}

	public Users(String username, String passwordsalt, String passwdhash, 
			Set<Packages> packageses, Set<Schedule> schedules) {
		this.username = username;
		this.passwdhash = passwdhash;
		this.packageses = packageses;
		this.schedules = schedules;
	}


	public String getPasswdhsah() {
		return passwdhash;
	}

	public void setPasswdhash(String passwdhash) {
		this.passwdhash = passwdhash;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}


	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}
	
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Set<Packages> getPackageses() {
		return this.packageses;
	}

	public void setPackageses(Set<Packages> packageses) {
		this.packageses = packageses;
	}

	
	public Set<Schedule> getSchedules() {
		return this.schedules;
	}

	public void setSchedules(Set<Schedule> schedules) {
		this.schedules = schedules;
	}

}
